### ISSUE TITLE
为啥监控没数据啊？

### ISSUE THREAD

**Issue by YunKillerE** [housepower/ckman#105]
监控都是空
![image](https://user-images.githubusercontent.com/12254857/122889430-5f64ad80-d375-11eb-8c32-6ab0cf4096f1.png)

prometheus是正常的
![image](https://user-images.githubusercontent.com/12254857/122889542-773c3180-d375-11eb-87ca-a571938af321.png)

ckman.conf
```
[root@data03 ck]# cat ckman/conf/ckman.yaml
server:
  id: 1
  port: 8808
  https: false
  pprof: true
  session_timeout: 3600
  #public_key:

log:
  level: INFO
  max_count: 5
  # megabyte
  max_size: 10
  # day
  max_age: 10

prometheus:
  hosts:
    - 127.0.0.1:9090
  # second
  timeout: 10

nacos:
  enabled: false
  hosts:
    - 127.0.0.1
  port: 8848
  user_name: nacos
  password: 0192023A7BBD73250516F069DF18B500
  #namespace:
  #group:
  #data_id:
```

这是哪里配置错了吗？

**Comment by zhbdesign** [comment]
![image](https://user-images.githubusercontent.com/50901800/123040916-21c05d00-d427-11eb-9481-15af53b14e6e.png)
这个要配置一下

**Comment by YunKillerE** [comment]
这里是不是ckman去查询prometheus展示啊？

把127.0.0.1改成prometheus的ip还是没有数据，图标都是空

**Comment by yuzhichang** [comment]
@YunKillerE prometheus要加一些配置才可以监控ck结点、zk结点等。

**Comment by YunKillerE** [comment]
@yuzhichang 要加啥配置啊？按找ckman部署的集群，暂不考虑zk节点的监控，clickhouse的9363端口也正常侦听，metrics也能获取出来，grafana能看到数据

目前已加配置：
```
  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
    - targets: ['data03:9100', 'data02:9100', 'data04:9100', 'data01:9100']

  - job_name: 'clickhouse'
    scrape_interval: 10s
    static_configs:
    - targets: ['data02:9363', 'data03:9363', 'data04:9363']

  - job_name: 'zookeeper'
    scrape_interval: 10s
    static_configs:
    - targets: ['data02:9141']

  - job_name: 'clickhouse_exporter'
    scrape_interval: 10s
    static_configs:
    - targets: ['data02:9116']

```

**Comment by zhbdesign** [comment]
> @yuzhichang 要加啥配置啊？按找ckman部署的集群，暂不考虑zk节点的监控，clickhouse的9363端口也正常侦听，metrics也能获取出来，grafana能看到数据
> 
> 目前已加配置：
> 
> ```
>   - job_name: 'node_exporter'
>     scrape_interval: 10s
>     static_configs:
>     - targets: ['data03:9100', 'data02:9100', 'data04:9100', 'data01:9100']
> 
>   - job_name: 'clickhouse'
>     scrape_interval: 10s
>     static_configs:
>     - targets: ['data02:9363', 'data03:9363', 'data04:9363']
> 
>   - job_name: 'zookeeper'
>     scrape_interval: 10s
>     static_configs:
>     - targets: ['data02:9141']
> 
>   - job_name: 'clickhouse_exporter'
>     scrape_interval: 10s
>     static_configs:
>     - targets: ['data02:9116']
> ```
prometheus:
  hosts: prometheusIP:9090
  # second
  timeout: 10
你是这样配置的吗

**Comment by YunKillerE** [comment]
> 
> 
> > @yuzhichang 要加啥配置啊？按找ckman部署的集群，暂不考虑zk节点的监控，clickhouse的9363端口也正常侦听，metrics也能获取出来，grafana能看到数据
> > 目前已加配置：
> > ```
> >   - job_name: 'node_exporter'
> >     scrape_interval: 10s
> >     static_configs:
> >     - targets: ['data03:9100', 'data02:9100', 'data04:9100', 'data01:9100']
> > 
> >   - job_name: 'clickhouse'
> >     scrape_interval: 10s
> >     static_configs:
> >     - targets: ['data02:9363', 'data03:9363', 'data04:9363']
> > 
> >   - job_name: 'zookeeper'
> >     scrape_interval: 10s
> >     static_configs:
> >     - targets: ['data02:9141']
> > 
> >   - job_name: 'clickhouse_exporter'
> >     scrape_interval: 10s
> >     static_configs:
> >     - targets: ['data02:9116']
> > ```
> 
> prometheus:
> hosts: prometheusIP:9090
> # second
> 
> timeout: 10
> 你是这样配置的吗

对的是这样配置的

```
prometheus:
  enabled: true
  hosts:
    - data02:9090
  # second
  timeout: 10

```

这事默认配置，这样配置有问题吗？该怎么改？谢谢！

**Comment by yuzhichang** [comment]
这里需要写明IP地址，例如：

```
  - job_name: 'clickhouse'
    scrape_interval: 10s
    static_configs:
    - targets: ['192.168.101.40:9363', '192.168.101.41:9363', '192.168.101.42:9363', '192.168.101.106:9363', '192.168.101.108:9363', '192.168.101.110:9363', '192.168.101.114:9363', '192.168.101.115:9363']

```

这样prometheus给每个target加类似`instance='192.168.101.40:9363'` 的label。ckman将用clickhouse集群各结点的IP来过滤这些lable。
