### ISSUE TITLE
ZooKeeper KPI的图渲染不出来

### ISSUE THREAD

**Issue by twoyang0917** [housepower/ckman#33]
目前的workaround

zookeeper需要作如下配置，重启。
```
## Metrics Providers
#
# https://prometheus.io Metrics Exporter
metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
metricsProvider.httpPort=7000
metricsProvider.exportJvmInfo=true
```

prometheus作如下配置，重启。
```
 - job_name: 'zk'
    scrape_interval: 10s
    static_configs:
    - targets: ['x.x.x.x:7000']
```
