### ISSUE TITLE
log 日志目录运行几天后占用空间特别大

### ISSUE THREAD

**Issue by IVitamin-C** [housepower/ckman#74]

**Comment by IVitamin-C** [comment]
![image](https://user-images.githubusercontent.com/35019926/118401015-9967d300-b696-11eb-8d7e-48a0fbafa7bb.png)
还有nocas
![image](https://user-images.githubusercontent.com/35019926/118401033-aab0df80-b696-11eb-913c-77871a2cf5e4.png)

**Comment by YenchangChan** [comment]
ckman的日志是支持rotate的，在这个地方可以设置日志的大小和rotate的个数 ：
```yaml
log:
  level: DEBUG
  max_count: 5
  max_size: 10
  max_age: 10
```
